extends Node

enum DAMAGE_TYPES { KINETIC, PARTICLE, FIRE, PARASITE }
enum SLOT_SIZES { SMALL, MEDIUM, LARGE }
enum SLOT_TYPES { ARMOR, FLEX, UTIL, WEAPON }

const GAME_IN_PROGRESS = "GAME_IN_PROGRESS"
const GAME_OVER = "GAME_OVER"
const GAME_STARTING = "GAME_STARTING"
